version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - python-compiler
      - java-compiler
      - cpp-compiler

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  python-compiler:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    volumes:
      - ./backend/docker_temp:/app

  java-compiler:
    build:
      context: ./backend
      dockerfile: Dockerfile.java
    volumes:
      - ./backend/docker_temp:/app

  cpp-compiler:
    build:
      context: ./backend
      dockerfile: Dockerfile.gcc
    volumes:
      - ./backend/docker_temp:/app
